### PR TITLE
some pep8 details in crossings.py

### PR DESCRIPTION
**Pull request by fchapoton**
just a few details

* first ran autopep8 on the file
* then tweak some code manually

### CODE REVIEW

**Comment by fchapoton** [comment]
ping ? :mask:

**Comment by NathanDunfield** [comment]
Sorry for the slow response, I forgot about this one.  I would prefer that the current lines 110 and 117 be reverted to closer to the original version.  I feel that "count % 2 == 0" and "count % 2 != 0" are clearer than "not count %2" and "count % 2" as they do not rely on the implicit conversion of an integer to a boolean.  If you make that change, I will merge ASAP.

**Comment by fchapoton** [comment]
ok, but this is slower

**Comment by slel** [comment]
Nathan, how about a version with a comment:

``` python
            # `if not count % 2` is faster than `if count % 2 == 0`
            if not count % 2 and over:  
```

``` python
            # `if count % 2` is faster than `if count % 2 == 1`
            if count % 2 and self.comp1 != self.comp2:
```

**Comment by NathanDunfield** [comment]
@fchapoton Thanks for the new commit.  I can't imagine speed of this particular comparison matters in the context of the whole program, but let me know if this is not the case.

**Pull request merged**
